// Mock data for when database connection is unavailable
export const mockBooks = [
  {
    id: 1,
    Title: "Book 1",
    Subtitle: "Freeing Allieria",
    author: "C. B. Reed",
    description:
      "Young Damien discovers on his 13th birthday that his entire world has been a lie, a year later he is still adjusting to his new life.",
    image_url: "/images/books/brothers-karamazov.jpg",
    genre: "Fantasy",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 2,
    title: "Book 2",
    Subtitle: "Freeing Allieria",
    author: "C. B. Reed",
    description:
      "Book 2 of Freeing Allieria series.",
    image_url: "/images/books/east-of-eden.jpg",
    genre: "Fantasy",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 3,
    title: "Book 3",
    Subtitle: "Freeing Allieria",
    author: "C. B. Reed",
    description:
      "Book 3 of Freeing Allieria series.",
    image_url: "/images/books/fifth-season.jpg",
    genre: "Science Fiction & Fantasy",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 4,
    ttitle: "Book 4",
    Subtitle: "Freeing Allieria",
    author: "C. B. Reed",
    description:
      "Book 4 of Freeing Allieria series.",
    image_url: "/images/books/jane-eyre.jpg",
    genre: "Literary Fiction",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 5,
    title: "TBA",
    Subtitle: "TBA",
    author: "C. B. Reed",
    description:
      "TBA.",
    image_url: "/images/books/anna-karenina.jpg",
    genre: "Literary Fiction",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 6,
    title: "TBA",
    Subtitle: "TBA",
    author: "C. B. Reed",
    description:
      "TBA.",
    image_url: "/images/books/giovannis-room.jpg",
    genre: "Historical Fiction",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 7,
    title: "TBA",
    Subtitle: "TBA",
    author: "C. B. Reed",
    description:
      "TBA.",
    image_url: "/images/books/my-brilliant-friend.jpg",
    genre: "Literary Fiction",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 8,
    title: "TBA",
    Subtitle: "TBA",
    author: "C. B. Reed",
    description:
      "TBA.",
    image_url: "/images/books/remains-of-the-day.jpg",
    genre: "Historical Fiction",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 9,
    title: "TBA",
    Subtitle: "TBA",
    author: "C. B. Reed",
    description:
      "TBA.",
    image_url: "/images/books/left-hand-of-darkness.jpg",
    genre: "Science Fiction & Fantasy",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];
